/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.EnviarCorreoControlador;
import modelo.Configuracion;

import javax.swing.*;
import util.ConfiguracionLoader;
/**
 *
 * @author delll
 */
public class Menu extends javax.swing.JFrame {

    private JButton buttonEnviarCorreo;
    private JButton buttonConfiguracion;
    private Configuracion configuracion;

    public Menu(Configuracion configuracion) {
        this.configuracion = configuracion;
        setTitle("Menu Principal");
        setSize(300, 200);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        inicializarComponentes();
        añadirListeners();
    }

    private void inicializarComponentes() {
        buttonEnviarCorreo = new JButton("Enviar Correo");
        buttonConfiguracion = new JButton("CambiarEnviarCorreoConf");

        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.add(buttonEnviarCorreo);
        panel.add(buttonConfiguracion);

        add(panel);
    }

    private void añadirListeners() {
        buttonEnviarCorreo.addActionListener(e -> abrirEnviarCorreoView());
        buttonConfiguracion.addActionListener(e -> abrirConfiguracionView());
    }

    private void abrirEnviarCorreoView() {
        EnviarCorreo enviarCorreoView = new EnviarCorreo(configuracion);
        new EnviarCorreoControlador(configuracion, enviarCorreoView);
        enviarCorreoView.setVisible(true);
        this.setVisible(false);
    }

    private void abrirConfiguracionView() {
        // Recargar la configuración manualmente
        Configuracion nuevaConfiguracion = ConfiguracionLoader.cargarConfiguracion();
        if (nuevaConfiguracion != null) {
            this.configuracion = nuevaConfiguracion;
            actualizarVista();
            JOptionPane.showMessageDialog(this, "Configuración recargada exitosamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Error al recargar la configuración.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void actualizarVista() {
        // Actualiza los elementos de la vista según la nueva configuración
        System.out.println("Nueva configuración cargada: " + configuracion.getServidores());
        // Actualiza componentes de la UI según los nuevos valores de configuración
    }
    /**
     * Creates new form Menu
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Enviar Correo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cambiar Conf");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 291, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
